<?php

namespace App\Models;

use App\HelperClasses\MyApp;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Model;

abstract class BaseModel extends Model
{
    public array $fieldsSearch = [];
    public array $fieldsLike = [];
    public array $fieldsFile = [];
    public array $fieldsIsNullable = [];

    /**
     * @author moner khalil
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $user = MyApp::Classes()->getUser();
            if (!is_null($user)) {
                $model->created_by = $user->id;
            }
        });
        self::updating(function ($model) {
            $user = MyApp::Classes()->getUser();
            if (!is_null($user)) {
                $model->updated_by = $user->id;
            }
        });
    }

    public function userCreatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, "created_by", "id");
    }

    public function userUpdatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, "updated_by", "id");
    }
}
